name: fluttour
description: Flutter is Googleâ€™s UI toolkit for building beautiful, natively compiled applications for mobile, web, and desktop from a single codebase. This template is created by dubydu.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  meta: ^1.1.8
  intl: ^0.16.1
  intl_translation: ^0.17.10+1
  flutter_screenutil: ^3.2.0
  flutter_spinkit: ^4.1.2+1
  fluttertoast: ^7.1.6
  flushbar: ^1.10.4
  provider: ^4.3.2+3
  logger: ^0.9.4
  tuple: ^1.0.3
  dio: ^3.0.10
  email_validator: ^1.0.6
  npreferences: ^3.0.0+1
  simple_animations: ^2.4.2

flutter_intl:
  enabled: true

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/base/icons/
    - assets/base/fonts/
    - assets/app/icons/
    - assets/app/fonts/